language: node_js
node_js:
  - '8'
cache: yarn
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: oeho/oDKqun0GmANXWqSPAy3U3IYFR1CcEx5lEwMMO5QlOB66E5iQXL7f36wtKAmNMs1DDmzzd9ws2OUMWNOuAKXjKJou1Hr7H74N35AaEoRz9PoAq6tl0dnVnGWz1pM71MpHKu6Qf+0gOYzfyqoo4Brs+SowWn3erwd2WgL6E2WTBDe/E9PYLyEnHryeqG2KQ1Y+ZLErEIBz3arHb896pGv1rfHQVzvgaLFqqciFcYt3UEyOrMGI9TVNvxloUstcKO+3Ujv/CcXzBM9auT/jLfs4bd59VTVgyfIEqlkZ8NNRQZA97H7/tTCWTfThJ9NuVioGtVy52DUUR9rI5F1i6xtDmg/A4INM7RH8+wKcOoFf3GsbyByvCUoL6wbz0o/74+6uYDETc/mMWgXjT8RSEByojDdS/8/AZB23cZ+4shsW9I9AME5XFY5CUlIFjANUTaph0aDN71kRrOEOIOzjUKAMSevC23HcSsKcDRW6yOA0Umt7MVB0N2qyfE9SLAV4MkVISaVNOqQaq0r2XsvujUD15n+yrl+/Ndhz3OvQkGf3rZ9BB/mqCfm7DuvaMwWlaczcvOJwJhAFTyD/SQbu/6alj2KYINUQPTnJZQJIws0gagsb3BYxuWwHANlROgvQ1vwYkH+OtVZx0RIUnYvxMLdWpEuUmAc15B8l7fuPE8=
  on:
    branch: master
  skip_cleanup: true