language: node_js
dist: focal
cache: yarn
before_script:
  - 'yarn lint'
notifications:
  email: false
deploy:
  provider: npm
  email: dev@launchpadlab.com
  api_key:
    secure: MtpU+a4OP5zRVFsQ2qm2J5xy1sR+yUa6xFKh4eRbDNBaOWGby4WnUem/Fua8xXI102ct9mqmgu3brCquyDIfkM6uY4qYknWtk3ofJvbCVySXWqws6KOcETLDp3w7fsAFFvHXuDVEuPjwnrE6N4r0X3nv1xGTLXfHff8Q7j0xiL6iwAIyEfLIv/XEZAS78WVCQ9IMRb3BPvOpLeqgHOupfBAYivA8bYfnv95fDLtRBsiQnBB4U1nU7VuP9LUn756pinqzneasYri3TtkOQmlvAtdpq9InY0WZycy1EhQTBu7lY1+Z+KHxQlaAO+JwAcNtKd6buv8/tlVWIHgKDik9Y1CaZxoVc33WBWmZ/PMrBa2DxWxNvPPN+dqQO+OMEfSoKJyCqJiF5qsb5gD0NXtCYQfszTtl2JkiRrSs0hW+WGNxYRZN/j6cJtmBN+zsuBIefM7iKfQMjH907nfGRRa8+h+7mqVmL2mikP4aEJjYPZe7WCd87asyUfOmvOoVsv+ZclBQ0J1wgE8b6o1JqYA1CfD619MZQB0AZG5dB+zRfI6U6FdQVnVtCx21o/fGdFlBZpiLzzgKjjLoxCP3cAzoGyjwzGyb5S/JXK5JQu7FQBgnDDx+rP8qWdCYzxpzAzbI65BFgJXgK6RsHBuudFSd6MVYpidRY78hkpmsi7aXhcU=
  on:
    branch: master
  skip_cleanup: true